"""Vendored gRPC stubs for the BOLT 12 gateway.

DO NOT EDIT files in this package by hand — they are generated by
``scripts/generate_bolt12_proto.sh`` from ``proto/bolt12_gateway.proto``.

Re-run that script whenever the .proto changes. The script also
rewrites the cross-module ``import bolt12_gateway_pb2`` line in the
generated ``*_grpc.py`` to use a relative import so the package works
when installed.
"""
