# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import bolt12_gateway_pb2 as bolt12__gateway__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in bolt12_gateway_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class Bolt12GatewayStub(object):
    """─── Service ───────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetIdentity = channel.unary_unary(
                '/bolt12_gateway.v1.Bolt12Gateway/GetIdentity',
                request_serializer=bolt12__gateway__pb2.GetIdentityRequest.SerializeToString,
                response_deserializer=bolt12__gateway__pb2.GetIdentityResponse.FromString,
                _registered_method=True)
        self.SendOnionMessage = channel.unary_unary(
                '/bolt12_gateway.v1.Bolt12Gateway/SendOnionMessage',
                request_serializer=bolt12__gateway__pb2.SendOnionMessageRequest.SerializeToString,
                response_deserializer=bolt12__gateway__pb2.SendOnionMessageResponse.FromString,
                _registered_method=True)
        self.StreamInbound = channel.unary_stream(
                '/bolt12_gateway.v1.Bolt12Gateway/StreamInbound',
                request_serializer=bolt12__gateway__pb2.StreamInboundRequest.SerializeToString,
                response_deserializer=bolt12__gateway__pb2.InboundOnionMessage.FromString,
                _registered_method=True)
        self.CreateBlindedPath = channel.unary_unary(
                '/bolt12_gateway.v1.Bolt12Gateway/CreateBlindedPath',
                request_serializer=bolt12__gateway__pb2.CreateBlindedPathRequest.SerializeToString,
                response_deserializer=bolt12__gateway__pb2.CreateBlindedPathResponse.FromString,
                _registered_method=True)
        self.ConnectPeer = channel.unary_unary(
                '/bolt12_gateway.v1.Bolt12Gateway/ConnectPeer',
                request_serializer=bolt12__gateway__pb2.ConnectPeerRequest.SerializeToString,
                response_deserializer=bolt12__gateway__pb2.ConnectPeerResponse.FromString,
                _registered_method=True)
        self.SetStickyPeers = channel.unary_unary(
                '/bolt12_gateway.v1.Bolt12Gateway/SetStickyPeers',
                request_serializer=bolt12__gateway__pb2.SetStickyPeersRequest.SerializeToString,
                response_deserializer=bolt12__gateway__pb2.SetStickyPeersResponse.FromString,
                _registered_method=True)
        self.SetKnownNodeAddresses = channel.stream_unary(
                '/bolt12_gateway.v1.Bolt12Gateway/SetKnownNodeAddresses',
                request_serializer=bolt12__gateway__pb2.NodeAddresses.SerializeToString,
                response_deserializer=bolt12__gateway__pb2.SetKnownNodeAddressesResponse.FromString,
                _registered_method=True)


class Bolt12GatewayServicer(object):
    """─── Service ───────────────────────────────────────────────────────

    """

    def GetIdentity(self, request, context):
        """Returns identity + peer state. Cheap; safe to poll for health.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendOnionMessage(self, request, context):
        """Send a single onion message. Returns once the message is enqueued
        for the relevant outbound peer; delivery is best-effort thereafter.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamInbound(self, request, context):
        """Server-streaming RPC: every inbound onion message addressed to
        *this* gateway (i.e. the receive end of one of our blinded paths)
        is pushed to the subscriber. Multiple subscribers fan-out is
        explicitly NOT supported in v1 — only the single Python service
        process is expected to consume.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBlindedPath(self, request, context):
        """Construct a blinded *message* path that terminates at this
        gateway, intended for inclusion in an offer's `offer_paths` or an
        invreq's `reply_path`. The caller specifies one or more public
        introduction-node candidates; the gateway picks one we're peered
        with and builds the path. The blinded-path bytes are returned
        ready to drop into a TLV.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConnectPeer(self, request, context):
        """Connect to a peer. Used to establish onion-message routing peers.
        Idempotent.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetStickyPeers(self, request, context):
        """Replace the gateway's "sticky peer" set. Sticky peers are the
        ones the gateway's on-disconnect handler will redial automatically
        with exponential backoff. Callers MUST push the full desired set
        on every call (REPLACE semantics, not add/remove) — that keeps
        the contract idempotent across gateway restarts: the wallet's
        periodic re-peer task re-pushes the current set, so a gateway
        that lost its in-memory cache rebuilds on the next push.

        Idempotent + crash-safe. The gateway treats this as advisory:
        it will still serve ConnectPeer calls for non-sticky peers, and
        sticky peers stay in the set until explicitly replaced.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetKnownNodeAddresses(self, request_iterator, context):
        """Push the known-peer address cache the gateway consults when LDK
        fires ``Event::ConnectionNeeded`` (outbound onion message
        buffered waiting for a peer we're not yet connected to) and
        neither the event hint nor the gateway's in-memory NetworkGraph
        has an address for the requested pubkey.

        The gateway's LDK NetworkGraph is intentionally empty (the
        ``route_handler`` is ``IgnoringMessageHandler`` — we don't
        consume gossip to keep the gateway's memory footprint small),
        so without this cache the gateway has no way to dial a peer
        it hasn't been told about. The wallet's LND DOES sync gossip;
        this RPC bridges that knowledge to the gateway.

        REPLACE semantics: each call overwrites the entire cache. The
        caller's freshness/staleness policy is authoritative — the
        gateway has no built-in periodic prune beyond the per-entry TTL
        enforced on lookup. Callers SHOULD push periodically (default
        1 h) so that addresses retired from LND's graph age out of the
        gateway's cache too.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Bolt12GatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetIdentity': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIdentity,
                    request_deserializer=bolt12__gateway__pb2.GetIdentityRequest.FromString,
                    response_serializer=bolt12__gateway__pb2.GetIdentityResponse.SerializeToString,
            ),
            'SendOnionMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendOnionMessage,
                    request_deserializer=bolt12__gateway__pb2.SendOnionMessageRequest.FromString,
                    response_serializer=bolt12__gateway__pb2.SendOnionMessageResponse.SerializeToString,
            ),
            'StreamInbound': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamInbound,
                    request_deserializer=bolt12__gateway__pb2.StreamInboundRequest.FromString,
                    response_serializer=bolt12__gateway__pb2.InboundOnionMessage.SerializeToString,
            ),
            'CreateBlindedPath': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBlindedPath,
                    request_deserializer=bolt12__gateway__pb2.CreateBlindedPathRequest.FromString,
                    response_serializer=bolt12__gateway__pb2.CreateBlindedPathResponse.SerializeToString,
            ),
            'ConnectPeer': grpc.unary_unary_rpc_method_handler(
                    servicer.ConnectPeer,
                    request_deserializer=bolt12__gateway__pb2.ConnectPeerRequest.FromString,
                    response_serializer=bolt12__gateway__pb2.ConnectPeerResponse.SerializeToString,
            ),
            'SetStickyPeers': grpc.unary_unary_rpc_method_handler(
                    servicer.SetStickyPeers,
                    request_deserializer=bolt12__gateway__pb2.SetStickyPeersRequest.FromString,
                    response_serializer=bolt12__gateway__pb2.SetStickyPeersResponse.SerializeToString,
            ),
            'SetKnownNodeAddresses': grpc.stream_unary_rpc_method_handler(
                    servicer.SetKnownNodeAddresses,
                    request_deserializer=bolt12__gateway__pb2.NodeAddresses.FromString,
                    response_serializer=bolt12__gateway__pb2.SetKnownNodeAddressesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bolt12_gateway.v1.Bolt12Gateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bolt12_gateway.v1.Bolt12Gateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Bolt12Gateway(object):
    """─── Service ───────────────────────────────────────────────────────

    """

    @staticmethod
    def GetIdentity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bolt12_gateway.v1.Bolt12Gateway/GetIdentity',
            bolt12__gateway__pb2.GetIdentityRequest.SerializeToString,
            bolt12__gateway__pb2.GetIdentityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendOnionMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bolt12_gateway.v1.Bolt12Gateway/SendOnionMessage',
            bolt12__gateway__pb2.SendOnionMessageRequest.SerializeToString,
            bolt12__gateway__pb2.SendOnionMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamInbound(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/bolt12_gateway.v1.Bolt12Gateway/StreamInbound',
            bolt12__gateway__pb2.StreamInboundRequest.SerializeToString,
            bolt12__gateway__pb2.InboundOnionMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateBlindedPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bolt12_gateway.v1.Bolt12Gateway/CreateBlindedPath',
            bolt12__gateway__pb2.CreateBlindedPathRequest.SerializeToString,
            bolt12__gateway__pb2.CreateBlindedPathResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConnectPeer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bolt12_gateway.v1.Bolt12Gateway/ConnectPeer',
            bolt12__gateway__pb2.ConnectPeerRequest.SerializeToString,
            bolt12__gateway__pb2.ConnectPeerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetStickyPeers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bolt12_gateway.v1.Bolt12Gateway/SetStickyPeers',
            bolt12__gateway__pb2.SetStickyPeersRequest.SerializeToString,
            bolt12__gateway__pb2.SetStickyPeersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetKnownNodeAddresses(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/bolt12_gateway.v1.Bolt12Gateway/SetKnownNodeAddresses',
            bolt12__gateway__pb2.NodeAddresses.SerializeToString,
            bolt12__gateway__pb2.SetKnownNodeAddressesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
