# SPDX-License-Identifier: MIT
"""Install-time artifact pinning — ``.env.example`` + ``start.sh``.

The Anonymize feature requires a non-trivial deployment posture (Fernet
keys, Tor SOCKS listener layout, optional operator-diversity URLs, etc.).
The install-time artifacts (``.env.example`` for manual deploys,
``start.sh`` for the interactive wizard) MUST stay in sync with
``app/core/config.py``. These tests pin:

* Every Fernet-key setting that the wallet refuses to start without is
  enumerated in ``.env.example`` and auto-generated by ``start.sh``.
* The curated alt-operator onions in ``start.sh`` match the API onions
  that were verified against ``/v2/version`` on the verification date.
  A silent rename or a typo'd hex character would route reverse swaps
  to an unintended host — failing the assertion is preferable to
  failing the deployment at first quote.
* The advisory copy in the wizard names the docs page operators
  can read for the threat model + diligence checklist.
"""

from __future__ import annotations

from pathlib import Path

_REPO = Path(__file__).resolve().parents[2]
_ENV_EXAMPLE = _REPO / ".env.example"
_START_SH = _REPO / "start.sh"


# ── Required env-keys ───────────────────────────────────────────────


# Knobs whose absence would cause the wallet to refuse to start an
# anonymize session. .env.example lists all of these explicitly; start.sh
# auto-generates the at-rest keys lazily. Format: env-var name → must
# appear in BOTH files (with or without a default value).
_REQUIRED_ANONYMIZE_KEYS = (
    # Master switches
    "ANONYMIZE_ENABLED",
    "ANONYMIZE_REQUIRE_TOR",
    "ANONYMIZE_ENFORCE_ONION_ONLY_EGRESS",
    # Amount + binning
    "ANONYMIZE_MIN_SAT",
    "ANONYMIZE_MAX_SAT",
    "ANONYMIZE_AMOUNT_BINS_SAT",
    # Tor listener layout
    "ANONYMIZE_TOR_SOCKS_PORTS",
    # At-rest encryption keys (REQUIRED in production)
    "ANONYMIZE_REUSE_DETECTION_KEY_FERNET",
    "ANONYMIZE_HOP_IDEMPOTENCY_KEY_FERNET",
    "ANONYMIZE_QUOTE_TOKEN_HMAC_KEY_FERNET",
    "ANONYMIZE_QUOTE_CACHE_SIGNING_KEY_FERNET",
    "ANONYMIZE_STEPUP_COOKIE_HMAC_KEY_FERNET",
    "ANONYMIZE_DECOY_SEED_FERNET",
    "ANONYMIZE_DECOY_SEED_ACCOUNT_KEY",
    # registry
    "ANONYMIZE_REGISTRY_RELEASE_KEY_FINGERPRINTS",
    "ANONYMIZE_REGISTRY_SIG_PATH",
    # Liquid + BIP-353
    "ANONYMIZE_LIQUID_ENABLED",
    "ANONYMIZE_LIQUID_SEED_FERNET",
    "ANONYMIZE_BIP353_DOH_ENDPOINT",
    "ANONYMIZE_BIP353_DEPOSIT_DOMAIN",
    "ANONYMIZE_EXT_LIGHTNING_DEPOSIT_METHOD",
    # Operator-diversity URLs (always present, blank by default)
    "BOLTZ_SUBMARINE_ONION_URL",
    "BOLTZ_REVERSE_ONION_URL",
)


def test_env_example_lists_required_anonymize_keys() -> None:
    """Every anonymize knob that a production deployment must consider
    appears in .env.example with a comment + default value (or blank)."""
    text = _ENV_EXAMPLE.read_text(encoding="utf-8")
    missing = [k for k in _REQUIRED_ANONYMIZE_KEYS if f"\n{k}=" not in text]
    assert not missing, f"missing keys from .env.example: {missing}"


def test_start_sh_emits_required_anonymize_keys() -> None:
    """start.sh writes every required key into the generated .env. The
    heredoc references the bash variable, so we look for ``KEY=${var}``."""
    text = _START_SH.read_text(encoding="utf-8")
    missing = [k for k in _REQUIRED_ANONYMIZE_KEYS if f"\n{k}=" not in text]
    assert not missing, f"missing keys from start.sh heredoc: {missing}"


# ── Curated alt-operator pin ───────────────────────────────


# Verified 2026-05-13 via `curl --socks5-hostname 127.0.0.1:9050` against
# /v2/version and /v2/swap/* — both return valid Boltz pair-info JSON.
# A regression here would point reverse swaps to an unintended host.
_MIDDLE_WAY_API_ONION = "middlwayksj5gak7pgaag32kcslzkjrpois57qtquiydpaqpy5fhzhqd.onion/v2"
_ELDAMAR_API_ONION = "mnyazp2duhs3jewqzw7g6vv44g73ijiujdmk5z6js72fn3epybup2yqd.onion/v2"


def test_start_sh_pins_middle_way_api_onion() -> None:
    """The Middle Way prompt is wired to its API onion (not the
    SwapMarket web-app frontend); a silent edit would silently route
    reverse swaps to an unintended host."""
    text = _START_SH.read_text(encoding="utf-8")
    assert _MIDDLE_WAY_API_ONION in text, "Middle Way API onion missing or mutated in start.sh"
    # The wizard MUST disclose the dead contact link so operators know
    # what they're trusting.
    assert "igit.me/middleway" in text
    assert "Middle Way" in text


def test_start_sh_pins_eldamar_api_onion() -> None:
    """The Eldamar prompt is wired to its API onion + the wizard names
    the liquidity limitation so a user picking it knows that bins above
    1M sat will fail at this operator."""
    text = _START_SH.read_text(encoding="utf-8")
    assert _ELDAMAR_API_ONION in text, "Eldamar API onion missing or mutated in start.sh"
    assert "Eldamar" in text
    # Liquidity-limit disclosure — bins ≥ 2.5M will fail.
    assert "≥ 2.5M" in text or "2_500_000" in text or "2500000" in text


def test_start_sh_advises_chain_skips_eldamar_for_large_bins() -> None:
    """Capacity pre-filter — Eldamar
    caps at 1M sat max-send. The chain logic skips Eldamar for bins
    that exceed its capacity; the install prose surfaces this so the
    user understands why their large-bin session never reaches Eldamar
    even when Middleway is unreachable.
    """
    text = _START_SH.read_text(encoding="utf-8")
    # The prose explains the per-bin skip without prescribing a
    # specific MAX_SAT change (the chain logic handles it
    # automatically per-quote rather than via a static cap).
    assert "the chain logic skips Eldamar" in text


def test_start_sh_references_operator_diversity_docs() -> None:
    """The wizard tells the user where to read about the threat
    model + the diligence checklist for evaluating an operator."""
    text = _START_SH.read_text(encoding="utf-8")
    assert "anonymize_operator_diversity.md" in text


def test_start_sh_canonical_boltz_on_reverse_leg() -> None:
    """The
    threat-model-correct assignment puts canonical Boltz (most
    vetted) on the REVERSE leg (where the destination address is
    visible) and curated alt operators on the SUBMARINE leg (which
    sees only the funding UTXO, which already assumes is
    identity-linked). A regression that flipped the legs would
    degrade destination privacy without alerting the user.

     the curated install does NOT pin URLs at all — it
    leaves both ``BOLTZ_*_ONION_URL`` blank so the chain-selection
    logic (operator_selection.py) governs the picks. The prose
    must explicitly explain the reverse=Boltz default so the
    operator reading the wizard understands which leg goes where.
    """
    text = _START_SH.read_text(encoding="utf-8")
    # The prose must state the canonical-on-reverse default.
    assert "canonical Boltz on the REVERSE leg" in text
    # And it must explain that the curated alt operators land on
    # the submarine leg with a fallback chain.
    assert "curated alt operators on the" in text
    # The default install MUST NOT pre-write either URL pin
    # (which would disable the fallback chain).
    assert 'boltz_reverse_onion_url="$_mw_onion"' not in text
    assert 'boltz_reverse_onion_url="$_eldamar_onion"' not in text
    assert 'boltz_submarine_onion_url="$_mw_onion"' not in text
    assert 'boltz_submarine_onion_url="$_eldamar_onion"' not in text


# ── Fernet auto-generation ───────────────────────────────────────────


def test_start_sh_auto_generates_required_fernet_keys() -> None:
    """When the user answers 'yes' to the Anonymize-enable prompt,
    start.sh auto-generates every at-rest Fernet key. Operators should
    NOT need to know how to invoke ``Fernet.generate_key()`` manually
    for a fresh install."""
    text = _START_SH.read_text(encoding="utf-8")
    # The generator helper uses the project's own ``cryptography`` dep.
    assert "from cryptography.fernet import Fernet" in text
    assert "Fernet.generate_key()" in text
    # Account-key (the HMAC key for decoy-seed derivation index) uses
    # a separate base64-random generator.
    assert "secrets.token_urlsafe(32)" in text


def test_start_sh_warns_about_backup_envelope_discipline() -> None:
    """The wizard warns operators that the anonymize at-rest keys must
    be backed up separately from the LND wallet seed. Mix-ups between
    the two are the primary operational risk (/ runbook)."""
    text = _START_SH.read_text(encoding="utf-8")
    assert "back up .env separately" in text.lower() or ("back up" in text.lower() and "separately" in text.lower())


# ── operators.json shape ──────────────────────────────────────


_OPERATORS_JSON_EXAMPLE = _REPO / "app" / "services" / "anonymize" / "operators.json.example"


def _load_example_registry():
    """Load the shipped operators.json.example through the same parser
    the wallet uses at runtime. The actual ``operators.json`` is only
    committed AFTER the maintainer signs it via
    ``scripts/sign_operator_registry.sh``; the .example template is
    what ships in-repo at v1."""
    import sys

    sys.path.insert(0, str(_REPO))
    from app.services.anonymize.operators import load_operator_registry

    return load_operator_registry(_OPERATORS_JSON_EXAMPLE)


def test_operators_json_example_exists_and_parses() -> None:
    """The shipped registry template parses through the wallet's own
    loader. A regression that introduced a malformed entry would
    refuse to start the anonymize service at boot once the maintainer
    signs + commits the matching operators.json."""
    assert _OPERATORS_JSON_EXAMPLE.is_file()
    entries = _load_example_registry()
    # Three pre-vetted operators ship at v1.
    assert len(entries) == 3
    op_ids = {e.operator_id for e in entries}
    assert op_ids == {"boltz-canonical", "middleway", "eldamar"}


def test_operators_json_onions_match_api_endpoints() -> None:
    """Each entry's onion URL points at the v2 API mount path that was
    verified live on 2026-05-13 via curl --socks5-hostname /version.
    A typo or accidental mount-path change would route swap requests
    to a 404 endpoint at runtime."""
    entries = {e.operator_id: e for e in _load_example_registry()}
    # Canonical Boltz mounts at /api/v2; community operators at /v2.
    assert entries["boltz-canonical"].onion.endswith(
        "boltzzzbnus4m7mta3cxmflnps4fp7dueu2tgurstbvrbt6xswzcocyd.onion/api/v2"
    )
    assert entries["middleway"].onion.endswith("middlwayksj5gak7pgaag32kcslzkjrpois57qtquiydpaqpy5fhzhqd.onion/v2")
    assert entries["eldamar"].onion.endswith("mnyazp2duhs3jewqzw7g6vv44g73ijiujdmk5z6js72fn3epybup2yqd.onion/v2")


def test_operators_json_signing_keys_blank_at_v1() -> None:
    """v1 ships with ``public_key_hex: ""`` for every entry because no
    operator emits ``X-Operator-Signature`` today. The wallet's
    verifier skips the check per-entry when the key is blank — when an
    operator eventually adopts response signing, editing the matching
    entry's ``public_key_hex`` + re-running the signing ceremony is
    the only required change. A regression that pre-populated a key
    here without the operator actually signing would cause every
    response from that operator to fail signature verification at
    runtime, silently breaking on-chain anonymize sessions for that
    leg."""
    for entry in _load_example_registry():
        assert entry.public_key_hex == "", (
            f"operator {entry.operator_id} has non-empty public_key_hex; "
            "v1 expects all entries to leave this blank (dormant)"
        )


def test_operators_json_attested_volume_zero_at_v1() -> None:
    """V1 ships with ``attested_min_24h_volume_satoshis: 0``
    for every entry because no operator publishes a 24h volume
    attestation. The scorer's volume-cap fires at `moderate` for any
    bin > 0 (which is every bin), which matches the existing
    no-distinct-operators cap for single-operator deployments. When
    an operator publishes an attestation we re-run the signing
    ceremony with the new number."""
    for entry in _load_example_registry():
        assert entry.attested_min_24h_volume_satoshis == 0


def test_sign_operator_registry_script_exists_and_executable() -> None:
    """The maintainer signing helper lives at scripts/sign_operator_registry.sh
    and is executable. The script computes the canonical bytes the
    wallet's signed-load path expects (file content rstrip'd of
    trailing whitespace + newlines, UTF-8 encoded — mirrors
    operators.py)."""
    script = _REPO / "scripts" / "sign_operator_registry.sh"
    assert script.is_file()
    import os

    assert os.access(script, os.X_OK), "script is not executable"
    text = script.read_text(encoding="utf-8")
    # The canonical-bytes formula MUST match operators.py exactly.
    assert "rstrip('\\n ')" in text or "rstrip(" in text
    assert ".encode('utf-8')" in text or '.encode("utf-8")' in text


# ── clock_skew_sources.json shape ──────────────────────────────


_CLOCK_SKEW_SOURCES_EXAMPLE = _REPO / "app" / "services" / "anonymize" / "clock_skew_sources.json.example"


def _load_example_clock_skew_sources():
    """Load the shipped clock_skew_sources.json.example through the same
    parser the wallet uses at runtime. The actual signed file is
    committed AFTER the maintainer runs the matching sign script."""
    import sys

    sys.path.insert(0, str(_REPO))
    from app.services.anonymize.clock_skew_sources import (
        load_clock_skew_sources,
    )

    return load_clock_skew_sources(_CLOCK_SKEW_SOURCES_EXAMPLE)


def test_clock_skew_sources_example_exists_and_parses() -> None:
    """The shipped clock-skew sources template parses through the
    wallet's own loader. A regression that introduced a malformed entry
    would break the probe's signed-fallback path at startup once the
    maintainer signs + commits the matching file."""
    assert _CLOCK_SKEW_SOURCES_EXAMPLE.is_file()
    entries = _load_example_clock_skew_sources()
    # v1 ships with 3 independent (non-swap-operator) sources so the
    # probe's median across responding sources defeats one misbehaving
    # one (threat model).
    assert len(entries) >= 2, (
        "clock-skew sources should ship with >=2 entries so the median "
        "across responding sources is robust to one misbehaving source"
    )
    # Each entry has the basic schema fields the loader requires.
    for entry in entries:
        assert entry.source_id, "source_id must not be empty"
        assert "://" in entry.url, f"entry {entry.source_id} url {entry.url!r} is not absolute"


def test_clock_skew_sources_independent_from_swap_operators() -> None:
    """The clock-skew threat model requires the source set to be
    independent of the swap-operator registry — a single compromised
    swap operator must NOT simultaneously appear as a clock-skew
    source. This test catches a regression where the curated lists
    accidentally overlap."""
    skew_urls = {e.url.rstrip("/") for e in _load_example_clock_skew_sources()}
    operator_urls = {e.onion.rstrip("/") for e in _load_example_registry()}
    overlap = skew_urls & operator_urls
    assert not overlap, f"clock-skew sources overlap swap-operator URLs: {overlap}"


def test_sign_clock_skew_sources_script_exists_and_executable() -> None:
    """The parallel signing helper for clock_skew_sources.json lives at
    scripts/sign_clock_skew_sources.sh and is executable. The script
    computes the canonical bytes the wallet's signed-load path expects
    (matches the formula in clock_skew_sources.py)."""
    script = _REPO / "scripts" / "sign_clock_skew_sources.sh"
    assert script.is_file()
    import os

    assert os.access(script, os.X_OK), "script is not executable"
    text = script.read_text(encoding="utf-8")
    assert "rstrip('\\n ')" in text or "rstrip(" in text
    assert ".encode('utf-8')" in text or '.encode("utf-8")' in text


# ── maintainer key bundling ───────────────────────────────────


_MAINTAINER_ASC = _REPO / "app" / "services" / "anonymize" / "maintainer.asc"
# v1 release-maintainer GPG fingerprint (Paul Lamb, https://paulscode.com).
# Published at https://paulscode.com/.well-known/paulscode.asc — the
# bundled maintainer.asc MUST match this fingerprint exactly. Forks
# replace BOTH the bundled .asc and this pinned value.
_V1_MAINTAINER_FP = "FF76D4843EBD7FA06D92DC0CB8AB7B8E7E280E1A"


def test_maintainer_asc_bundled() -> None:
    """The signed-registry loader imports the bundled
    ``app/services/anonymize/maintainer.asc`` into an isolated GPG
    keyring at verify time. The file MUST be present in the repo —
    a missing file would force every signed-registry deployment to
    manually transfer the public key into their host's GPG keyring
    and would defeat the wallet's self-contained verification."""
    assert _MAINTAINER_ASC.is_file()
    armored = _MAINTAINER_ASC.read_text(encoding="utf-8")
    assert armored.startswith("-----BEGIN PGP PUBLIC KEY BLOCK-----")
    assert "-----END PGP PUBLIC KEY BLOCK-----" in armored


def test_maintainer_asc_fingerprint_matches_pin() -> None:
    """The bundled maintainer.asc's primary-key fingerprint MUST match
    the pinned value in .env.example + start.sh. A drift between the
    two would cause every signed-registry load to fail with
    'no pinned fingerprint matches' even though the signature is
    technically valid."""
    import os
    import shutil
    import subprocess
    import tempfile

    gpg = shutil.which("gpg") or shutil.which("gpg2")
    if gpg is None:
        import pytest

        pytest.skip("no gpg binary — can't verify maintainer.asc fingerprint")

    with tempfile.TemporaryDirectory(prefix="anon-key-check-") as gpg_home:
        os.chmod(gpg_home, 0o700)
        subprocess.run(
            [gpg, "--homedir", gpg_home, "--batch", "--no-tty", "--import", str(_MAINTAINER_ASC)],
            check=True,
            capture_output=True,
            timeout=10,
        )
        out = subprocess.run(
            [gpg, "--homedir", gpg_home, "--with-colons", "--fingerprint"],
            check=True,
            capture_output=True,
            timeout=10,
        )
        primary_fp = None
        for line in out.stdout.decode().splitlines():
            if line.startswith("fpr:"):
                primary_fp = line.split(":")[9]
                break
        assert primary_fp == _V1_MAINTAINER_FP, (
            f"bundled maintainer.asc fingerprint {primary_fp} does NOT match pinned default {_V1_MAINTAINER_FP}"
        )


def test_env_example_pins_v1_maintainer_fingerprint() -> None:
    """The shipped .env.example pins the v1 maintainer fingerprint
    as the default for `ANONYMIZE_REGISTRY_RELEASE_KEY_FINGERPRINTS`.
    Forks who change maintainer.asc MUST also change this — the
    test pin keeps the two coupled."""
    env_text = _ENV_EXAMPLE.read_text(encoding="utf-8")
    assert f"ANONYMIZE_REGISTRY_RELEASE_KEY_FINGERPRINTS={_V1_MAINTAINER_FP}" in env_text


def test_start_sh_pins_v1_maintainer_fingerprint() -> None:
    """start.sh's get_env default for the registry fingerprint matches
    the v1 maintainer fingerprint."""
    text = _START_SH.read_text(encoding="utf-8")
    assert _V1_MAINTAINER_FP in text
